# Generated by Django 5.0.4 on 2024-06-07 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauranttable', '0002_auto_add_initial_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(),
        ),
    ]
