# Generated by Django 5.0.4 on 2024-06-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
